import importlib.util
import os
import tempfile
import unittest
from pathlib import Path

MODULE_PATH = (
    Path(__file__).resolve().parents[1]
    / "files/4-apps/home/rinkhals/apps/40-moonraker/mmu_ace_metadata.py"
)
MODULE_NAME = "testsupport.moonraker.components.mmu_ace_metadata"


def _load_module():
    spec = importlib.util.spec_from_file_location(MODULE_NAME, MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


metadata_module = _load_module()

SLICER_HEADER = "; generated by OrcaSlicer 2.4.2 on 2026-01-01 at 00:00:00\n"
# The line newer OrcaSlicer emits that gklib mis-parses (slice-bounds panic,
# surfaced as error 10111).
BAD_LINE = "; filament_colour_type = 0;0;0;0\n"


def _build_gcode(multi_tool, include_bad_line):
    lines = [SLICER_HEADER, "G28\n"]
    if multi_tool:
        lines += ["T0\n", "G1 X1 Y1\n", "T1\n", "G1 X2 Y2\n"]
    else:
        lines += ["G1 X1 Y1\n", "G1 X2 Y2\n"]
    if include_bad_line:
        lines.append(BAD_LINE)
    lines.append("; end of gcode\n")
    return "".join(lines)


class ParseGcodeFileTests(unittest.TestCase):
    """parse_gcode_file must report whether a gklib-hostile line is present."""

    def _parse(self, multi_tool, include_bad_line):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "test.gcode")
            with open(path, "w") as handle:
                handle.write(_build_gcode(multi_tool, include_bad_line))
            return metadata_module.parse_gcode_file(path)

    def test_detects_strippable_line_on_single_tool_file(self):
        result = self._parse(multi_tool=False, include_bad_line=True)
        self.assertEqual(result["tools_used"], [])
        self.assertTrue(result["needs_strip"])

    def test_no_strip_flag_when_file_is_clean(self):
        result = self._parse(multi_tool=False, include_bad_line=False)
        self.assertEqual(result["tools_used"], [])
        self.assertFalse(result["needs_strip"])

    def test_detects_tools_and_strippable_line_together(self):
        result = self._parse(multi_tool=True, include_bad_line=True)
        self.assertEqual(result["tools_used"], [0, 1])
        self.assertTrue(result["needs_strip"])


class ProcessFileTests(unittest.TestCase):
    """process_file strips gklib-hostile lines, and only stamps MMU metadata
    when the file actually uses tools."""

    def _process(self, multi_tool, include_bad_line):
        with tempfile.TemporaryDirectory() as tmp:
            src = os.path.join(tmp, "in.gcode")
            dst = os.path.join(tmp, "out.gcode")
            with open(src, "w") as handle:
                handle.write(_build_gcode(multi_tool, include_bad_line))
            parsed = metadata_module.parse_gcode_file(src)
            metadata_module.process_file(
                src, dst, parsed["tools_used"], parsed["total_toolchanges"]
            )
            with open(dst) as handle:
                return handle.read()

    def test_single_tool_file_is_stripped_without_mmu_metadata(self):
        # The whole point of the fix: a single-tool file still gets the
        # unparseable line removed, but is otherwise left alone.
        output = self._process(multi_tool=False, include_bad_line=True)
        self.assertNotIn("filament_colour_type", output)
        self.assertNotIn(metadata_module.MMU_ACE_FINGERPRINT, output)
        self.assertNotIn("referenced_tools", output)
        self.assertIn("G1 X1 Y1", output)
        self.assertIn("; end of gcode", output)

    def test_multi_tool_file_is_stripped_and_stamped(self):
        output = self._process(multi_tool=True, include_bad_line=True)
        self.assertNotIn("filament_colour_type", output)
        self.assertTrue(output.startswith(metadata_module.MMU_ACE_FINGERPRINT))
        self.assertIn("; referenced_tools = 0,1", output)

    def test_no_empty_referenced_tools_comment(self):
        # Guards against emitting "; referenced_tools = " with no tools.
        output = self._process(multi_tool=False, include_bad_line=True)
        self.assertNotIn("referenced_tools =", output)


class StripIdempotencyTests(unittest.TestCase):
    def test_reprocessing_a_stripped_file_needs_no_further_strip(self):
        with tempfile.TemporaryDirectory() as tmp:
            src = os.path.join(tmp, "in.gcode")
            dst = os.path.join(tmp, "out.gcode")
            with open(src, "w") as handle:
                handle.write(_build_gcode(multi_tool=False, include_bad_line=True))
            parsed = metadata_module.parse_gcode_file(src)
            metadata_module.process_file(
                src, dst, parsed["tools_used"], parsed["total_toolchanges"]
            )
            reparsed = metadata_module.parse_gcode_file(dst)
            self.assertFalse(reparsed["needs_strip"])


if __name__ == "__main__":
    unittest.main()
